###
# This is the place to override the haproxy cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "haproxy/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the HA-Proxy stats url and user:
#
#normal[:haproxy][:stats_url] = '/haproxy?stats'
#normal[:haproxy][:stats_user] = 'opsworks'
rhel_arch = RUBY_PLATFORM.match(/64/) ? 'x86_64' : 'i686'
normal[:haproxy][:version] = '1.5.11'
normal[:haproxy][:rpm] = "haproxy-#{node[:haproxy][:version]}-#{node[:haproxy][:patchlevel]}.#{rhel_arch}.rpm"
normal[:haproxy][:rpm_url] = "#{node[:opsworks_commons][:assets_url]}/packages/#{node[:platform]}/#{node[:platform_version]}/#{node[:haproxy][:rpm]}"
